# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9723d4c68f64d3677da12f85e20e98487abc1759f5b7fde7b925f79ddabec337790ace3c1638c7fc6819ee1e7a0d5a7cc834a8c3fe1461ae135af084f8669108

test:
  secret_key_base: 3b94ce9ca864dda24bbd4892452777c699473ec83215f30f8cbed883ff1578c6b7b79bf901461221239ca4551e177492990d8982a7373c7f0bec46b047836a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
